name: 'nyc_taxi_dbt_eda'
version: '1.0'
config-version: 2

profile: 'nyc_taxi_dbt_eda'

models:
  nyc_taxi_dbt_eda:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

seeds:
  nyc_taxi_dbt_eda:
    +schema: seeds
